version: '{build}'

hosts:
  mariadb.example.com: 127.0.0.1

environment:
  LINT: 0
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
  MUST_USE_TCPIP: 1
  TEST_HOST: mariadb.example.com
  TEST_LOG_PACKETS: true
  matrix:

    - DB: '10.4.6'
      MEM: "21"
      nodejs_version: "8"

    - DB: '10.4.6'
      MEM: "21"
      nodejs_version: "10"

    - DB: '10.4.6'
      MEM: "21"
      nodejs_version: "12"
      SKIP_LEAK: "1"

    - DB: '10.4.6'
      nodejs_version: "12"
      MEM: "21"
      TEST_ZIP: 1
      SKIP_LEAK: "1"

    - DB: '10.4.6'
      nodejs_version: "12"
      MEM: "21"
      BENCH: "1"
      SKIP_LEAK: "1"

    - DB: '10.3.16'
      MEM: "21"
      nodejs_version: "12"
      SKIP_LEAK: "1"

    - DB: '10.2.25'
      MEM: "21"
      nodejs_version: "12"
      SKIP_LEAK: "1"

    - DB: '10.1.40'
      MEM: "21"
      nodejs_version: "12"
      SKIP_LEAK: "1"

    - DB: '10.0.38'
      MEM: "21"
      nodejs_version: "12"
      SKIP_LEAK: "1"

    - DB: '5.5.64'
      MEM: "5"
      nodejs_version: "12"
      SKIP_LEAK: "1"

cache:
  - node_modules

clone_folder: c:\projects\mariadb-connector-nodejs

install:
  - cmd: set FILE=http://ftp.hosteurope.de/mirror/archive.mariadb.org//mariadb-%DB%/winx64-packages/mariadb-%DB%-winx64.msi
  - ps: Start-FileDownload $Env:FILE -FileName server.msi
  - cmd: msiexec /i server.msi INSTALLDIR=c:\projects\server SERVICENAME=mariadb ALLOWREMOTEROOTACCESS=true /qn
  - cmd: "\"c:\\projects\\server\\bin\\mysql.exe\" -e \"create database testn\" --user=root"
  - cmd: echo [mysqld] > c:\projects\server\data\my.ini
  - cmd: echo datadir=C:/projects/server/data >> c:\projects\server\data\my.ini
  - cmd: echo port=3306 >> c:\projects\server\data\my.ini
  - cmd: echo innodb_buffer_pool_size=2037M >> c:\projects\server\data\my.ini
  - cmd: echo innodb_log_file_size=%MEM%0m >> c:\projects\server\data\my.ini
  - cmd: echo max_allowed_packet=%MEM%m >> c:\projects\server\data\my.ini
  - cmd: echo bind-address=0.0.0.0 >> c:\projects\server\data\my.ini
  - cmd: echo character-set-server=utf8mb4 >> c:\projects\server\data\my.ini
  - cmd: echo collation_server=utf8mb4_unicode_ci >> c:\projects\server\data\my.ini
  - cmd: echo ssl_ca=c:\projects\mariadb-connector-nodejs\test\certificats\ca.crt >> c:\projects\server\data\my.ini
  - cmd: echo ssl_cert=c:\projects\mariadb-connector-nodejs\test\certificats\server.crt >> c:\projects\server\data\my.ini
  - cmd: echo ssl_key=c:\projects\mariadb-connector-nodejs\test\certificats\server.key >> c:\projects\server\data\my.ini
  - cmd: echo enable-named-pipe=1 >> c:\projects\server\data\my.ini
  - cmd: type c:\projects\server\data\my.ini
  - ps: Restart-Service "mariadb"
  - ps: Install-Product node $env:nodejs_version
  - cmd: cd c:\projects\mariadb-connector-nodejs
  - cmd: npm install

build: off

test_script:
  - node --version
  - if "%SKIP_LEAK%" == "" npm install node-memwatch
  - if "%BENCH%" == "1" ( npm install microtime ) else ( npm test )
  - if "%BENCH%" == "1" ( npm install promise-mysql mysql2 )
  - if "%BENCH%" == "1" ( node c:\projects\mariadb-connector-nodejs\benchmarks\benchmarks.js )
