version: '2.1'
services:
  maxscale:
    depends_on:
      - db
    ports:
      - 4006:4006
      - 4007:4007
      - 4008:4008
    build:
      context: .
      dockerfile: maxscale/Dockerfile
      args:
        MAXSCALE_VERSION: $MAXSCALE_VERSION
  db:
    image: $DB
    command: --max-connections=500 --max-allowed-packet=40m --innodb-log-file-size=400m --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --ssl-ca=/etc/sslcert/ca.crt --ssl-cert=/etc/sslcert/server.crt --ssl-key=/etc/sslcert/server.key --bind-address=0.0.0.0
    ports:
      - 3305:3306
    volumes:
      - $SSLCERT:/etc/sslcert
      - $ENTRYPOINT:/pam
    environment:
      MYSQL_DATABASE: testj
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
